[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/quarkus-app/quarkus-run.jar"

[build.environment]
JAVA_VERSION = "21"

[[services]]
name = "web"
[services.source]
type = "image"

[services.env]
PORT = "8080"